import type { Metadata, Viewport } from "next";
import Script from "next/script";
import "../../public/assets/css/plugins/swiper-bundle.min.css";
import "../../public/assets/css/plugins/glightbox.min.css";
import "../../public/assets/css/google_fonts.css"
import "../../public/assets/css/vendor/bootstrap.min.css";
import "../../public/assets/css/style.css";
import Header from "@/components/header/header";
import IndexFooter from "@/components/index_page/IndexFooter";
import Loader from "@/components/loader/loader";
// import { Inter } from "next/font/google";
// import "./globals.css";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Grosser",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  initialScale: 1,
  width: "device-width"
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <ScrollToTop />

        <IndexFooter />
        {/* //! this(glightbox) is causing the hydration error for some reason, */}
        {/* //? More to look into it*/}
        <Script src="/assets/js/vendor/popper.js" />
        <Script src="/assets/js/vendor/bootstrap.min.js" />
        <Script src="/assets/js/plugins/swiper-bundle.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/plugins/glightbox.min.js" strategy="beforeInteractive" />
        <Script src="/assets/js/script.js" />
      </body>
    </html>
  );
}

function ScrollToTop() {
  return (
    <button id="scroll__top"><svg xmlns="http://www.w3.org/2000/svg" className="ionicon" viewBox="0 0 512 512">
      <path fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="48"
        d="M112 244l144-144 144 144M256 120v292" />
    </svg></button>
  )
}

