name: Build Check
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "16.20.2"
    
    - name: Install dependencies
      run: npm cli

    - name: Run build
      run: npm run build